[config]
colors_to_properties = true

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/configs/colors.conf"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-theme.css"
output_path = "~/.config/waybar/theme.css"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-theme.conf"
output_path = "~/.config/kitty/theme.conf"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/style.css"

[templates.kde]
input_path = "~/.config/matugen/templates/kde-colorscheme.colors"
output_path = "~/.local/share/color-schemes/MatugenDynamic.colors"
post_hook = "command -v plasma-apply-colorscheme >/dev/null && pgrep -x plasmashell >/dev/null && plasma-apply-colorscheme MatugenDynamic || true"

[templates.kvantum_svg]
input_path = "~/.config/matugen/templates/kvantum-theme.svg"
output_path = "~/.config/Kvantum/KvMatugen/KvMatugen.svg"

[templates.kvantum_config]
input_path = "~/.config/matugen/templates/kvantum-theme.kvconfig"
output_path = "~/.config/Kvantum/KvMatugen/KvMatugen.kvconfig"
