general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
}

listener {
    timeout = 240                              # 4min
    on-timeout = pidof hyprlock || uwsm-app -- xdg-terminal-exec -e cmatrix -s -C green
    on-resume = pkill cmatrix
}

listener {
    timeout = 300                              # 5min
    on-timeout = loginctl lock-session         # lock screen
}

listener {
    timeout = 330                              # 5.5min
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0
    on-resume = brightnessctl -rd '*::kbd_backlight'
}

listener {
    timeout = 330                              # 5.5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
